### ISSUE TITLE
Number of extracted SIFT features CPU vs GPU

### ISSUE THREAD

**Issue by MoritzMKB** [alicevision/AliceVision#1074]
Hi, I noticed that the number of extracted features can differ quite substantially when switching from cpu to gpu.

For example, for the first two images of the buddha dataset [0], 11857 and 11286 sift features were extracted, respectively, when using the gpu (--forceCpuExtraction 0).

However, I get 20000 features when using the cpuversion (--forceCpuExtraction 1). For some other images I noticed the discrepancy to be as large as 1:10. Apart from the forceCpuExtraction command I used the default arguments in both cases.

I am using meshroom 2021.1.0 for windows [1].

[0] https://github.com/alicevision/dataset_buddha
[1] https://www.fosshub.com/Meshroom.html?dwl=Meshroom-2021.1.0-win64.zip

**Comment by fabiencastan** [comment]
Yes, because we filter the number of extracted points on cpu at the end.
For performance reason, we filter the points earlier on gpu, before extracting the feature orientations.
So as a feature point may exist with multiple orientations, you could have a bit more features on gpu than on cpu.

But the variation should be quite limited, 1 to 10 is clearly not possible. If you have a dataset that allow to reproduce that, it would be interesting to debug.
