### ISSUE TITLE
Failed to estimate space from SfM: The space bounding box is too small

### ISSUE THREAD

**Issue by juniorrrrrrr** [alicevision/AliceVision#1117]
Hi, I have this same problem in Meshing:
"Failed to estimate space from SfM: The space bounding box is too small"
Searching around here I already tried to disable the "Estimate Space From Sfm" but it didn't work, I tried again with other photos, without success either.
How can I resolve this gap?
I use version 2021.01
Is my machine too weak?
650 Ti
Core 2 Quad Q8200

**Comment by natowi** [comment]
What kind of dataset are you trying to reconstruct? Do you see a point cloud when the StructureFromMotion node completes? Pleas try to reconstruct the reference dataset from https://github.com/alicevision/dataset_monstree (mini3 suffices) If it reconstructs fine, than the issue is most likely with your dataset.
