### ISSUE TITLE
Can the spherical panorama collected by Ladybug camera be reconstructed directly with alicevision?

### ISSUE THREAD

**Issue by zhulz** [alicevision/AliceVision#1182]

**Comment by natowi** [comment]
If you can get the original images prior stitching, use those. Otherwise you could split the panorama back into separate images (aliceVision_utils_split360Images.exe)

In Meshroom, there is some basic support for multi camera rigs: https://github.com/alicevision/meshroom/wiki/Multi-Camera-Rig You could try to use the same folder structure and use a folder as input from the cli.
