### ISSUE TITLE
Curiosità su NVIDIA NeRFs

### ISSUE THREAD

**Issue by Marcor1975** [alicevision/AliceVision#1400]
Salve ! A seguito della nascita del sistema creato dalla NVIDIA ..Iastant NeRFs...  mi chiedevo se era possibile utilizzare Alicevison/Mashroom per cerare il file "*.Json" contenente le posizioni e dati delle telecamere, al posto di utilizzare Colmap...che fancamente non mi piace!
Grazie per l'attenzione.

**Comment by simogasp** [comment]
In the develop branch and in the upcoming release of Alicevision there is this utility binary that takes a abc/sfm/json (alicevision scene format) and converts it into the colmap format so that it can be fed to nerf algorithms
https://github.com/alicevision/AliceVision/blob/develop/src/software/export/main_exportColmap.cpp

**Comment by MarcoRos75** [comment]
OK!  Grazie Simone ! Aspetterò con ansia!!!

**Comment by natowi** [comment]
And https://github.com/joreeves/mr2nerf

**Comment by MarcoRos75** [comment]
Ciao Natowi....!   Grazie!  Proverò ad usare questo metodo..!!!
