### ISSUE TITLE
dependencies/osi_clp should be updated

### ISSUE THREAD

**Issue by mia-0** [alicevision/AliceVision#433]
Upstream has, among other things, fixes for a couple string buffer overflows that really should be applied.

**Comment by simogasp** [comment]
This has been fixed in https://github.com/alicevision/AliceVision/pull/1237
The libs are not internal dependencies anymore, we rely on our fork that has a CMakeLists similar to that used by vcpkg, see CoinUtils, Osi and Clp at https://github.com/alicevision/CoinUtils, https://github.com/alicevision/Osi and https://github.com/alicevision/Clp.
