### ISSUE TITLE
Improve Feature Matching performance with the integration of hnswlib 

### ISSUE THREAD

**Issue by AmirYalamov** [alicevision/AliceVision#821]
We want to improve Feature Matching in the Alice Vision pipeline with the use of the [hnswlib library](https://github.com/nmslib/hnswlib), which uses a Small World search method to find the nearest neighbour.

We will be going off the [example implementation](https://github.com/openMVG/openMVG/commit/a1565ed9b6b3530e1b95c0a608c4f4a5eacb0bcf#diff-5e6c6fbd5d2cd5cb74137761c6161938R47) (shoutout to @rjanvier for the awesome work :tada:) provided by @fabiencastan.

This will be worked on by @AmirYalamov and @honsontran.

Pull request soon to come.

@flosincapite @simogasp

**Comment by pmoulon** [comment]
https://github.com/openMVG/openMVG/commit/a1565ed9b6b3530e1b95c0a608c4f4a5eacb0bcf#diff-5e6c6fbd5d2cd5cb74137761c6161938R47 Would be nice to give some credits to @rjanvier that made the integration into OpenMVG ;-)

**Comment by rjanvier** [comment]
We have some "not yet pushed changes" regarding performance issues on Windows (due to some "flaws" in SIMD detection on this plateform)  and also a "better" integration with openMVG SIMD kernels. For now,  Windows performance is not on par with Linux/OSX perf. I hope we'll have the time to merge these fixes in the public branch of openMVG soon.

**Comment by AmirYalamov** [comment]
Pull Request has been made: #836 @flosincapite @simogasp @fabiencastan
